// Generated by Wrangler by running `wrangler types --env-interface CloudflareBindings`
// This is a stub. Run `pnpm cf-typegen` to regenerate with real runtime types and bindings.
interface CloudflareBindings {}
