name: Setup Node & pnpm
description: Node.js と pnpm をセットアップし、依存関係をインストールする

inputs:
  node-version:
    description: セットアップする Node.js のバージョン
    required: false
    default: '24.12.0'
  pnpm-version:
    description: セットアップする pnpm のバージョン
    required: false
    default: '10.26.0'

runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
      with:
        version: ${{ inputs.pnpm-version }}

    - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
      with:
        node-version: ${{ inputs.node-version }}
        cache: pnpm

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile
